project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
files:
  - source: public/locales/en-US/grafana.json
    translation: public/locales/ru-RU/grafana.json
    type: i18next_json
